/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormDnevniRaspored;

import FormPlesac.*;
import FormTrening.FormNoviTrening;
import controller.ClientController;
import domain.DnevniRaspored;
import domain.Plesac;
import domain.Trening;
import forms.MainForm;
import java.net.SocketException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.PieChart;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import models.TableModelTreninziDnevnog;

/**
 *
 * @author PC
 */
public class FormDetaljiDnevnogRasporeda extends javax.swing.JDialog {

    /**
     * Creates new form FormIzmenaTrenera
     */
    private DnevniRaspored dr;

    public FormDetaljiDnevnogRasporeda(JFrame parent, boolean modal, DnevniRaspored dr) {
        super(parent, modal);
        initComponents();
        this.dr = dr;
        setLocationRelativeTo(null);
        lblDnevniRasporedID.setText("Dnevni raspored ID: " + String.valueOf(dr.getDnevniRasporedID()));
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        lblDatum.setText(sdf.format(dr.getDatum()));
        tblTreninzi.setModel(new TableModelTreninziDnevnog(dr));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblDnevniRasporedID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTreninzi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnObrisiTrening = new javax.swing.JButton();
        btnDodajTrening = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOtkazi.setBackground(new java.awt.Color(255, 204, 204));
        btnOtkazi.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(255, 204, 204));
        btnObrisi.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        btnObrisi.setText("Obrisi dnevni raspored");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblDnevniRasporedID.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        lblDnevniRasporedID.setText("DnevniRasporedID");

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel1.setText("Datum:");

        lblDatum.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        lblDatum.setText("Datum:");

        tblTreninzi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTreninzi);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 15)); // NOI18N
        jLabel2.setText("Treninzi");

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel3.setText("Pretraga:");

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        btnObrisiTrening.setBackground(new java.awt.Color(255, 204, 204));
        btnObrisiTrening.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        btnObrisiTrening.setText("Obrisi trening");
        btnObrisiTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiTreningActionPerformed(evt);
            }
        });

        btnDodajTrening.setBackground(new java.awt.Color(255, 204, 204));
        btnDodajTrening.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        btnDodajTrening.setText("Dodaj trening");
        btnDodajTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajTreningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDnevniRasporedID)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblDatum))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addComponent(jLabel2))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnObrisiTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDodajTrening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDnevniRasporedID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblDatum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiTrening)
                    .addComponent(btnDodajTrening))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnObrisi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Dnevni raaspored je prazan. "
                + "Da li ste sigurni da zelite da "
                + "obrisete ovaj dnevni raspored?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                TableModelTreninziDnevnog tm = (TableModelTreninziDnevnog) tblTreninzi.getModel();
                dr.setListaTreninga((ArrayList<Trening>) tm.getLista());
                ClientController.getInstance().deleteDnevniRaspored(dr);
                MainForm mf = (MainForm) getParent();
                mf.osveziTabelu();
                JOptionPane.showMessageDialog(this, "Uspesno obrisan dnevni raspored!");
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(FormDetaljiDnevnogRasporeda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String param = txtPretraga.getText();
        ((TableModelTreninziDnevnog) tblTreninzi.getModel()).setParametar(param);
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnObrisiTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiTreningActionPerformed

        int selectedRow = tblTreninzi.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan red!");
            return;
        }

        TableModelTreninziDnevnog tm = (TableModelTreninziDnevnog) tblTreninzi.getModel();
        Trening t = tm.getSelectedTrening(selectedRow);

        try {
            ClientController.getInstance().deleteTrening(t);
            tm.refreshTable();
            if(tm.getLista().isEmpty()){
                btnObrisiActionPerformed(evt);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Uspesno obrisan trening.");
            }
        } catch (Exception ex) {
            Logger.getLogger(FormDetaljiDnevnogRasporeda.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnObrisiTreningActionPerformed

    private void btnDodajTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajTreningActionPerformed
        if(dr.getDatum().before(new Date(System.currentTimeMillis())) || dr.getDatum().equals(new Date(System.currentTimeMillis())))
        {
            JOptionPane.showMessageDialog(this, "Dnevni raspored mora biti posle danasnjeg datuma!");
            return;
        }
        
        new FormNoviTrening(this, true).setVisible(true);
    }//GEN-LAST:event_btnDodajTreningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDetaljiDnevnogRasporeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDetaljiDnevnogRasporeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDetaljiDnevnogRasporeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDetaljiDnevnogRasporeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajTrening;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiTrening;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDnevniRasporedID;
    private javax.swing.JTable tblTreninzi;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void dodajTrening(Trening t) {
        t.setDr(dr);
        TableModelTreninziDnevnog tm = (TableModelTreninziDnevnog) tblTreninzi.getModel();
        int rb = 0;
        
        for (Trening trening : tm.getLista()) {
            rb++;
        }
        
        t.setRb(++rb);
        
        try {
            ClientController.getInstance().addTrening(t);
            tm.refreshTable();
            JOptionPane.showMessageDialog(this, "Uspesno dodat trening.");
        } catch (Exception ex) {
            Logger.getLogger(FormDetaljiDnevnogRasporeda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
