/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import FormAdministrator.FormNoviAdministrator;
import FormAdministrator.FormPretragaAdministratora;
import FormDnevniRaspored.FormDetaljiDnevnogRasporeda;
import FormDnevniRaspored.FormNoviDnevniRaspored;
import FormPlesac.FormNoviPlesac;
import FormPlesac.FormPretragaPlesaca;
import com.sun.security.ntlm.Client;
import controller.ClientController;
import domain.Administrator;
import domain.Trener;
import FormTrener.FormNoviTrener;
import FormTrener.FormPretragaTrenera;
import domain.DnevniRaspored;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelDnevniRaspored;
import session.Session;

/**
 *
 * @author 38160
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        Administrator a = Session.getInstance().getTrenutnoUlogovaniAdministrator();
        lblUlogovani.setText("Trenutno ulogovani administrator: "
                + a.getIme() + " " + a.getPrezime());
        TableModelDnevniRaspored model = new TableModelDnevniRaspored();
        Thread th = new Thread(model);
        th.start();
        tblDnevniRaspored.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDnevniRaspored = new javax.swing.JTable();
        btnDodajDnevniRaspored = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JFormattedTextField();
        btnDetalji = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuNoviPlesac = new javax.swing.JMenuItem();
        menuPretragaPlesaca = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuNoviTrener = new javax.swing.JMenuItem();
        menuPretragaTrenera = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miNoviAdmin = new javax.swing.JMenuItem();
        miPretragaAdmina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 11)); // NOI18N
        lblUlogovani.setText("jLabel1");

        tblDnevniRaspored.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        tblDnevniRaspored.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDnevniRaspored);

        btnDodajDnevniRaspored.setBackground(new java.awt.Color(255, 204, 204));
        btnDodajDnevniRaspored.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        btnDodajDnevniRaspored.setText("Dodaj dnevni raspored");
        btnDodajDnevniRaspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDnevniRasporedActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel1.setText("Datum:");

        txtDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatum.setText("21.06.2021");

        btnDetalji.setBackground(new java.awt.Color(255, 204, 204));
        btnDetalji.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        btnDetalji.setText("Detalji dnevnog raspored");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        jMenu2.setText("Plesaci");

        menuNoviPlesac.setText("Novi plesac");
        menuNoviPlesac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoviPlesacActionPerformed(evt);
            }
        });
        jMenu2.add(menuNoviPlesac);

        menuPretragaPlesaca.setText("Pretraga plesaca");
        menuPretragaPlesaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaPlesacaActionPerformed(evt);
            }
        });
        jMenu2.add(menuPretragaPlesaca);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Treneri");

        menuNoviTrener.setText("Novi trener");
        menuNoviTrener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoviTrenerActionPerformed(evt);
            }
        });
        jMenu1.add(menuNoviTrener);

        menuPretragaTrenera.setText("Pretraga trenera");
        menuPretragaTrenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaTreneraActionPerformed(evt);
            }
        });
        jMenu1.add(menuPretragaTrenera);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Administratori");

        miNoviAdmin.setText("Novi administrator");
        miNoviAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviAdminActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviAdmin);

        miPretragaAdmina.setText("Pretraga administratora");
        miPretragaAdmina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaAdminaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaAdmina);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatum))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUlogovani)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodajDnevniRaspored, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnDodajDnevniRaspored)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalji)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPretragaTreneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaTreneraActionPerformed
        new FormPretragaTrenera(this, true).setVisible(true);
    }//GEN-LAST:event_menuPretragaTreneraActionPerformed

    private void menuNoviTrenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoviTrenerActionPerformed
        new FormNoviTrener(this, true).setVisible(true);
    }//GEN-LAST:event_menuNoviTrenerActionPerformed

    private void miNoviAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviAdminActionPerformed
        if (Session.getInstance().getTrenutnoUlogovaniAdministrator().getAdministratorID() == 1) {
            new FormNoviAdministrator(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nemate pristup ovoj operaciji!");
        }
    }//GEN-LAST:event_miNoviAdminActionPerformed

    private void miPretragaAdminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaAdminaActionPerformed
        if (Session.getInstance().getTrenutnoUlogovaniAdministrator().getAdministratorID() == 1) {
            new FormPretragaAdministratora(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nemate pristup ovoj operaciji!");
        }
    }//GEN-LAST:event_miPretragaAdminaActionPerformed

    private void menuNoviPlesacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoviPlesacActionPerformed
        new FormNoviPlesac(this, true).setVisible(true);
    }//GEN-LAST:event_menuNoviPlesacActionPerformed

    private void menuPretragaPlesacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaPlesacaActionPerformed
        new FormPretragaPlesaca(this, true).setVisible(true);
    }//GEN-LAST:event_menuPretragaPlesacaActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        int selectedRow = tblDnevniRaspored.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan red!");
            return;
        }

        TableModelDnevniRaspored tm = (TableModelDnevniRaspored) tblDnevniRaspored.getModel();
        DnevniRaspored dr = tm.getSelectedDnevniRaspored(selectedRow);

        new FormDetaljiDnevnogRasporeda(this, true, dr).setVisible(true);
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnDodajDnevniRasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDnevniRasporedActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            Date datum = sdf.parse(txtDatum.getText());

            if (datum.before(new Date(System.currentTimeMillis()))
                    ) {
                JOptionPane.showMessageDialog(this, "Datum mora da bude posle danasnjeg datuma!");
                return;
            }

            DnevniRaspored dr = new DnevniRaspored(Long.MIN_VALUE, datum, null);

            new FormNoviDnevniRaspored(this, true, dr).setVisible(true);

        } catch (ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnDodajDnevniRasporedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnDodajDnevniRaspored;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem menuNoviPlesac;
    private javax.swing.JMenuItem menuNoviTrener;
    private javax.swing.JMenuItem menuPretragaPlesaca;
    private javax.swing.JMenuItem menuPretragaTrenera;
    private javax.swing.JMenuItem miNoviAdmin;
    private javax.swing.JMenuItem miPretragaAdmina;
    private javax.swing.JTable tblDnevniRaspored;
    private javax.swing.JFormattedTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    public void osveziTabelu() {
        TableModelDnevniRaspored tm = (TableModelDnevniRaspored) tblDnevniRaspored.getModel();
        tm.refreshTable();
    }

}
